services:
  postgress_db_drivenops:
    image: postgres
    container_name: postgress_db_drivenops
    restart: always
    ports:
      - 4475:5432
    env_file:
      - ./back-end/.env.test
    
  node_drivenops: 
    container_name: node_drivenops
    build: ./back-end
    ports:
      - 5000:5000
    depends_on:
      - postgress_db_drivenops
    env_file:
      - ./back-end/.env.test
  